name: CI Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up UTF-8 and PowerShell output
        shell: pwsh
        run: |
          $OutputEncoding = [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          Write-Host "Using PowerShell version: $($PSVersionTable.PSVersion)"

      - name: Build EXE, move to root, UPX and create ZIP
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'

          $ahkCompiler = "ahk\\Compiler\\Ahk2Exe.exe"
          $baseFile    = "ahk\\Compiler\\Unicode 32-bit.bin"
          $input       = "rpcl3ac.ahk"
          $output      = "rpcl3ac.exe"
          $icon        = "rpcl3_media\\rpcl3_default.ico"
          $toolsFolder = "rpcl3_tools"
          $zipName     = "rpcl3ac_release.zip"
          $repoRoot    = $env:GITHUB_WORKSPACE

          $extraAssets = @(
            "README.txt",
            "LICENSE"
          )

          $requiredFiles = @(
            $ahkCompiler,
            $baseFile,
            $input,
            "$toolsFolder\\vgmstream-cli.exe"
          )

          foreach ($file in $requiredFiles) {
            if (!(Test-Path $file)) {
              Write-Error ":: Required file not found: $file"
              exit 1
            }
            Write-Host ":: Found: $file"
          }

          # --- Compile ---
          & $ahkCompiler /in $input /out $output /icon $icon /base $baseFile

          $compiledExe = Join-Path $PWD $output
          $finalExe    = Join-Path $repoRoot $output

          if ((Test-Path $compiledExe) -and ($compiledExe -ne $finalExe)) {
            Move-Item $compiledExe $finalExe -Force
            Write-Host ":: Moved EXE to $finalExe"
          }

          if (!(Test-Path $finalExe)) {
            $knownGood = "D:\\a\\rpcl3-atrac-converter\\rpcl3-atrac-converter\\rpcl3ac.exe"
            if (Test-Path $knownGood) {
              Copy-Item $knownGood $finalExe -Force
              Write-Host ":: Recovered EXE from fallback: $knownGood"
            }
          }

          if (!(Test-Path $finalExe)) {
            Write-Error ":: Build failed — EXE still not found at $finalExe"
            exit 1
          }

          # --- UPX compression ---
          if (Test-Path "upx\\upx.exe") {
            & "upx\\upx.exe" --best --lzma $finalExe
          }

          # --- ZIP packaging ---
          $toZip = @($finalExe)

          if (Test-Path $toolsFolder) {
            $toolsFiles = Get-ChildItem -Path $toolsFolder -Recurse -File | Select-Object -ExpandProperty FullName
            $toZip += $toolsFiles
            Write-Host "Added $($toolsFiles.Count) tool files"
          } else {
            Write-Warning ":: Tools folder not found: $toolsFolder"
          }

          foreach ($asset in $extraAssets) {
            $assetAbs = Join-Path $repoRoot $asset
            if (Test-Path $assetAbs) {
              $toZip += $assetAbs
              Write-Host ":: Added asset to zip: $assetAbs"
            } else {
              Write-Warning ":: Missing asset, not added: $assetAbs"
            }
          }

          Compress-Archive -Path $toZip -DestinationPath (Join-Path $repoRoot $zipName) -Force

      - name: Upload EXE and ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rpcl3ac.exe
            rpcl3ac_release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
